# Starting from base image
FROM node:22-alpine3.21 AS BUILDER
WORKDIR /app
COPY ./package* ./
RUN npm install
COPY . .
RUN npm run build:v2


FROM node:22-alpine3.21
WORKDIR /app
COPY package* ./

# install only production dependencies
RUN npm install --omit=dev
COPY --from=BUILDER /app/dist ./dist

ENTRYPOINT [ "npm", "run", "start:v2" ]

