services:
  db:
    container_name: dock-demo-db
    image: mariadb:11
    restart: on-failure
    environment:
      MARIADB_USER: dock-demo
      MARIADB_PASSWORD: dock-demo
      MARIADB_DATABASE: dock-demo
      MARIADB_ROOT_PASSWORD: dd-docker-demo
    networks:
      - docker-demo

  svc:
    container_name: svc
    image: dock-demo
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.v3
    ports:
      - "8080:3050"
    depends_on:
      - db
    environment:
      PORT: 3050
      DB_NAME: dock-demo
      DB_USER: root
      DB_PASS: dd-docker-demo
      DB_HOST: db
      DB_PORT: 3306
      INIT_DB: true
    networks:
      - docker-demo

networks:
  docker-demo:
